[tool.pyright]
typeCheckingMode = "strict"

[tool.ruff]
select = ["ALL"]
ignore = ["S101", "G004", "FBT002", "FBT001", "PLR0913", "PLR0915", "EM102", "C901"]
line-length = 300
[tool.ruff.per-file-ignores]
"setup.py" = ["INP001"]
